"""Add partial unique index PipelineVersion

Revision ID: 06669eb017db
Revises: 5809fcbdf4ca
Create Date: 2026-01-19 01:03:21.258974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06669eb017db'
down_revision: Union[str, Sequence[str], None] = '5809fcbdf4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_pipeline_version', 'pipelineversions', ['pipeline_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_pipeline_version', table_name='pipelineversions', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###
