"""Add owners

Revision ID: 5809fcbdf4ca
Revises: bcac65ee097c
Create Date: 2026-01-11 16:57:17.389894

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '5809fcbdf4ca'
down_revision: Union[str, Sequence[str], None] = 'bcac65ee097c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_owners',
    sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'user_id')
    )
    op.drop_index('ix_pipelines_user_id', table_name='pipelines')
    op.drop_constraint('pipelines_user_id_fkey', 'pipelines', type_='foreignkey')
    op.drop_column('pipelines', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('pipelines_user_id_fkey', 'pipelines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_pipelines_user_id', 'pipelines', ['user_id'], unique=False)
    op.drop_table('pipeline_owners')
    # ### end Alembic commands ###
