"""Add all models

Revision ID: 6c5b036ca1a8
Revises: 99ff4074f29f
Create Date: 2026-01-09 17:21:05.211455

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c5b036ca1a8'
down_revision: Union[str, Sequence[str], None] = '99ff4074f29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelineversions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelineversions_id'), 'pipelineversions', ['id'], unique=False)
    op.create_index(op.f('ix_pipelineversions_pipeline_id'), 'pipelineversions', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipelineversions_version'), 'pipelineversions', ['version'], unique=False)
    op.create_table('pipelineruns',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pipeline_version_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='pipelinerunstatus'), nullable=False),
    sa.Column('executor_run_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_version_id'], ['pipelineversions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelineruns_executor_run_id'), 'pipelineruns', ['executor_run_id'], unique=False)
    op.create_index(op.f('ix_pipelineruns_id'), 'pipelineruns', ['id'], unique=False)
    op.create_index(op.f('ix_pipelineruns_pipeline_id'), 'pipelineruns', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipelineruns_pipeline_version_id'), 'pipelineruns', ['pipeline_version_id'], unique=False)
    op.create_index(op.f('ix_pipelineruns_status'), 'pipelineruns', ['status'], unique=False)
    op.create_index(op.f('ix_pipelineruns_user_id'), 'pipelineruns', ['user_id'], unique=False)
    op.alter_column('pipelines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipelines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'updated_at')
    op.alter_column('pipelines', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipelines', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pipelineruns_user_id'), table_name='pipelineruns')
    op.drop_index(op.f('ix_pipelineruns_status'), table_name='pipelineruns')
    op.drop_index(op.f('ix_pipelineruns_pipeline_version_id'), table_name='pipelineruns')
    op.drop_index(op.f('ix_pipelineruns_pipeline_id'), table_name='pipelineruns')
    op.drop_index(op.f('ix_pipelineruns_id'), table_name='pipelineruns')
    op.drop_index(op.f('ix_pipelineruns_executor_run_id'), table_name='pipelineruns')
    op.drop_table('pipelineruns')
    op.drop_index(op.f('ix_pipelineversions_version'), table_name='pipelineversions')
    op.drop_index(op.f('ix_pipelineversions_pipeline_id'), table_name='pipelineversions')
    op.drop_index(op.f('ix_pipelineversions_id'), table_name='pipelineversions')
    op.drop_table('pipelineversions')
    # ### end Alembic commands ###
