"""Add user for pipeline

Revision ID: bcac65ee097c
Revises: cdbec2dcb1b1
Create Date: 2026-01-09 21:57:54.088329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bcac65ee097c'
down_revision: Union[str, Sequence[str], None] = 'cdbec2dcb1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_pipelines_user_id'), 'pipelines', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pipelines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'runartifacts', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runartifacts', type_='unique')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_index(op.f('ix_pipelines_user_id'), table_name='pipelines')
    op.drop_column('pipelines', 'user_id')
    # ### end Alembic commands ###
