"""Add RunArtifact model

Revision ID: cdbec2dcb1b1
Revises: 9882eb099a6b
Create Date: 2026-01-09 19:27:31.086490

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdbec2dcb1b1'
down_revision: Union[str, Sequence[str], None] = '9882eb099a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runartifacts',
    sa.Column('pipeline_run_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'LINK', 'TEXT', 'JSON', name='typeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipelineruns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runartifacts')
    # ### end Alembic commands ###
